name: Publish to VSCode Marketplace


on:
  push:
    tags:
      - "*"
  workflow_dispatch: 

jobs:
  vsce-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install
      - name: Publish to VSCode Marketplace
        run: npx vsce publish