name: Publish to VSCode Marketplace


on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  vsce-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get NodeJS
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npx vsce publish